name: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.5

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: set nx base and head ref
      uses: nrwl/nx-set-shas@v4

    - name: log nx base and head ref
      run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
      shell: bash

    - name: pnpm install node modules
      run: pnpm i --frozen-lockfile
      shell: bash

    - name: pnpm build
      run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build
      shell: bash
