#!/bin/bash

# Function to display help
usage() {
  echo "Usage: $0 [-j json_file] [-o output_file] [-v variable prefix]"
  echo "  -j    Specify the contract json file (inside the out directory)"
  echo "  -o    Specify the output file name (written to src/abis)"
  echo "  -v    Specify the prefix of the output variable"
  echo "  -h    Display this help message"
  exit 1
}

# Parse flags
while getopts "v:j:o:h" opt; do
  case ${opt} in
    v )
      VARIABLE_PREFIX=$OPTARG
      ;;
    j )
      JSON_FILE=$OPTARG
      ;;
    o )
      OUTPUT_FILE=$OPTARG
      ;;
    h )
      usage
      ;;
    \? )
      usage
      ;;
  esac
done

# Run forge build and extract bytecode and ABI
bytecode=$(forge build --silent > /dev/null 2>&1 && jq '.bytecode.object' $JSON_FILE)
abi=$(forge build --silent > /dev/null 2>&1 && jq '.abi' $JSON_FILE)

# Check if the commands succeeded
if [ $? -ne 0 ]; then
  echo "Failed to extract bytecode or ABI from JSON file."
  exit 1
fi

# Create ABI directory if it does not exist
mkdir -p $ABI_DIR

# Write to the output file
{
  echo "// DO NOT MODIFY! THIS FILE IS AUTOGENERATED. See package.json for generation scripts."
  echo "export const ${VARIABLE_PREFIX}ByteCode = $bytecode;"
  echo "export const ${VARIABLE_PREFIX}Abi = $abi as const;"
} > "$OUTPUT_FILE"

echo "ABI and bytecode have been saved to $OUTPUT_FILE"
