version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -q -U api-key-service@oplabs-local-web.iam -d api-key-service',
        ]
    volumes:
      - ./setup-local-db.sql:/docker-entrypoint-initdb.d/setup-local-db.sql
    ports:
      - '5432:5432'

  api-key-service:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: api-key-service
    env_file: .env
    healthcheck:
      test: wget localhost:7330/healthz -q -O - > /dev/null 2>&1
    ports:
      - 7330:7330
