version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - ./setup-local-db.sql:/docker-entrypoint-initdb.d/setup-local-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U local-db-user -d event-log-indexer']
  
  indexer:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: event-log-indexer
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgresql://local-db-user:@postgres:5432/event-log-indexer
    volumes:
      - ../../certs/extra-ca-certificates.crt:/usr/local/share/ca-certificates/extra-ca-certificates.crt
    ports:
      - "42069:42069"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
