// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import { defineChain } from 'viem'
import * as viemChains from 'viem/chains'
import { chainConfig } from 'viem/op-stack'

import { contracts as chainContracts } from '@/chains/contracts.js'
import type { Network } from '@/chains/types.js'
import { contracts as opContracts } from '@/contracts.js'

/**
 * Chain Definition for Arena Z Sepolia
 */
export const arenaZSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Arena Z Sepolia',
  id: 9899,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://testnet-rpc.arena-z.gg'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Arena Z Sepolia Explorer',
      url: 'https://testnet-explorer.arena-z.gg',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[9899] ? chainContracts[11155111][9899] : {}),
    portal: {
      11155111: {
        address: '0x90FdCE6eFFF020605462150cdE42257193d1e558',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x23592510F948c1465294041b44192f9656146544',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x0aB6D908f5553732fBbC2e5b25357E9202c396BA',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x3E0252828c920C21C5F1b86f862444295F5f283C',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x5357bE2D78aAd17860570E14B74561840e959D4D',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xd02dd46b73ff5f3eC3970f9A12f08Ad703c103df',
      },
    },
  },
})

/**
 * Chain Definition for Base Sepolia
 */
export const baseSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Base Sepolia',
  id: 84532,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.base.org'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Base Sepolia Explorer',
      url: 'https://sepolia-explorer.base.org',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[84532]
      ? chainContracts[11155111][84532]
      : {}),
    portal: {
      11155111: {
        address: '0x49f53e41452C74589E85cA1677426Ba426459e85',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xfd0Bf71F60660E2f608ed56e1659C450eB113120',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x21eFD066e581FA55Ef105170Cc04d74386a09190',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xC34855F4De64F1840e5686e64278da901e261f20',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xf272670eb55e895584501d564AfEB048bEd26194',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xd6E6dBf4F7EA0ac412fD8b65ED297e64BB7a06E1',
      },
    },
  },
})

/**
 * Chain Definition for Boba Sepolia
 */
export const bobaSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Boba Sepolia',
  id: 28882,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.boba.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Boba Sepolia Explorer',
      url: 'https://testnet.bobascan.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[28882]
      ? chainContracts[11155111][28882]
      : {}),
    portal: {
      11155111: {
        address: '0xB079E6FA9B3eb072fEbf7F746044834eab308dB6',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x244d7b81EE3949788Da5F1178D911e83bA24E157',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x13B397A08322973B45e063F29746Fb278f189916',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x9253E76E2fA3f72aF18e08914b3528F725779495',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xfDC9bCE032cEF55a71b4fde9B9a2198ad1551965',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x29Bd67B23cAC0E6bbDe1373E3859Dd25510f3331',
      },
    },
  },
})

/**
 * Chain Definition for Camp Network  V2 Sepolia
 */
export const campSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Camp Network  V2 Sepolia',
  id: 325000,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.camp-network-testnet.gelato.digital'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Camp Network  V2 Sepolia Explorer',
      url: 'https://camp-network-testnet.blockscout.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[325000]
      ? chainContracts[11155111][325000]
      : {}),
    portal: {
      11155111: {
        address: '0x4238fAb3746D41e18c87138b505B6857CeF6cd1F',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x5c3Ec2182Be9FbeA0da50d517362a069e13FB50E',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x1239F374612F4674305ba7c60332b16e5396e125',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x3f4A9443DdC60a0d0Dcea92C627849045B5A840f',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x7aA405B004401Be20d4A587de34aEeC99bE0b268',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x83BaE25FDa209b31E903D3DD932906E2718A6E89',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0x6AD70b6C30Aa872FcbB86958A6aB950b3125a6f0',
      },
    },
  },
})

/**
 * Chain Definition for Creator Chain Sepolia
 */
export const creatorChainSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Creator Chain Sepolia',
  id: 66665,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.creatorchain.io'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Creator Chain Sepolia Explorer',
      url: 'https://explorer.creatorchain.io',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[66665]
      ? chainContracts[11155111][66665]
      : {}),
    portal: {
      11155111: {
        address: '0x1Cb215554f36f518791B2e7359a73c96bFcadf69',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x78558fd5C8DC65D10753f004Bfc4cFA8E199C668',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xe82526042dae3F8800f87232b5146ED4012eE426',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x19f3D95A281F9Cf6aA2c6e8b7cA7c6Be83e41F3A',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x978e8311A5A710ef6413abA3A6b89092ce4a58f5',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x156670e48F72cB23EAadd8b51e398c678AB651aF',
      },
    },
  },
})

/**
 * Chain Definition for Cyber Sepolia
 */
export const cyberSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Cyber Sepolia',
  id: 111557560,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.testnet.cyber.co'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Cyber Sepolia Explorer',
      url: 'https://testnet.cyberscan.co/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[111557560]
      ? chainContracts[11155111][111557560]
      : {}),
    portal: {
      11155111: {
        address: '0x06C9Cadb0346c8E142fb8299cEF3EB5120d4c9b6',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xAA1bD6D4d8cFD37330a917bc678CB38BEFAf44E6',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xB88ee11d822bEc8055f19711458dE8593E7117A3',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x43b838Aa237B27c4fC953E591594CEBb1CA2817F',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x99f0f9B0E7B16B10042E0935CE34F2fCebBE13C1',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0xD94Ce9E4886A6dcEbC7cF993f4b38F5276516643',
      },
    },
  },
})

/**
 * Chain Definition for Ethernity Sepolia
 */
export const ethernitySepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Ethernity Sepolia',
  id: 233,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://testnet.ethernitychain.io'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Ethernity Sepolia Explorer',
      url: 'https://testnet.ernscan.io',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[233] ? chainContracts[11155111][233] : {}),
    portal: {
      11155111: {
        address: '0x1F24d471Ef7291c7F97DBD2f76299b30D3e3B6E3',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xFd1a12b7a04B13c031d8b075BA5b9080a2CF246f',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xBf0D43e12eF74dC21917e1D6175702AD673e1283',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x1c8b6a6F3E3612c79E62460a6e44C24D1EfF2FDa',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x7C957fec1F6B3d1024442E989cB08b8f2285686C',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x64d0Bce6eD7c16CAC7817F3597758E31AFacD01B',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0x11118536F94Bc7C98bBaf9194bE13FC1987293cd',
      },
    },
  },
})

/**
 * Chain Definition for Funki Sepolia
 */
export const funkiSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Funki Sepolia',
  id: 3397901,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://funki-testnet.alt.technology'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Funki Sepolia Explorer',
      url: 'https://sepolia-sandbox.funkichain.com/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[3397901]
      ? chainContracts[11155111][3397901]
      : {}),
    portal: {
      11155111: {
        address: '0xCeE7ef4dDF482447FE14c605Ea94B37cBE87Ca9D',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x1ba82f688eF3C5B4363Ff667254ed4DC59E97477',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x598D245Ea85FBfBceCe6c62232bbCAB688D3F68b',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x6F82D895E223Dde65DA28a8bbD14f3eF79cBF3b8',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xd6A01f1Ef51D65F023433992a8F62fEeAD35b172',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xEc7C6E35f4e5361D279d5Fe7222F3F45A8A83352',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0xB25812386D1Cb976b50de7387F5CBc10Fec3F27c',
      },
    },
  },
})

/**
 * Chain Definition for Ink Sepolia
 */
export const inkSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Ink Sepolia',
  id: 763373,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc-gel-sepolia.inkonchain.com'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Ink Sepolia Explorer',
      url: 'https://explorer-sepolia.inkonchain.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[763373]
      ? chainContracts[11155111][763373]
      : {}),
    portal: {
      11155111: {
        address: '0x5c1d29C6c9C8b0800692acC95D700bcb4966A1d7',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x33f60714BbD74d62b66D79213C348614DE51901C',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xd1C901BBD7796546A7bA2492e0E199911fAE68c7',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x9fE1d3523F5342535E6E7770ED09ed85Dbc1Acc2',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x05C993e60179f28bF649a2Bb5b00b5F4283bD525',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x860e626c700AF381133D9f4aF31412A2d1DB3D5d',
      },
    },
  },
})

/**
 * Chain Definition for Lisk Sepolia
 */
export const liskSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Lisk Sepolia',
  id: 4202,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.sepolia-api.lisk.com'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Lisk Sepolia Explorer',
      url: 'https://sepolia-blockscout.lisk.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[4202] ? chainContracts[11155111][4202] : {}),
    portal: {
      11155111: {
        address: '0xe3d90F21490686Ec7eF37BE788E02dfC12787264',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x1Fb30e446eA791cd1f011675E5F3f5311b70faF5',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xb4E988CF1aD8C361D56118437502A8f11C7FaA01',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x857824E6234f7733ecA4e9A76804fd1afa1A3A2C',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xF54791059df4a12BA461b881B4080Ae81a1d0AC0',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x9AA3890a87E6BD2CB85Dad1A5D8B0A9D669e658a',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0xA0E35F56C318DE1bD5D9ca6A94Fe7e37C5663348',
      },
    },
  },
})

/**
 * Chain Definition for Metal L2 Sepolia
 */
export const metalSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Metal L2 Sepolia',
  id: 1740,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://testnet.rpc.metall2.com'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Metal L2 Sepolia Explorer',
      url: 'https://testnet.explorer.metall2.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[1740] ? chainContracts[11155111][1740] : {}),
    portal: {
      11155111: {
        address: '0x01D4dfC994878682811b2980653D03E589f093cB',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x21530aAdF4DCFb9c477171400E40d4ef615868BE',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x5d6cE6917dBeeacF010c96BfFdaBE89e33a30309',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x5D335Aa7d93102110879e3B54985c5F08146091E',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x5D63A8Dc2737cE771aa4a6510D063b6Ba2c4f6F2',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xd9A68F90B2d2DEbe18a916859B672D70f79eEbe3',
      },
    },
  },
})

/**
 * Chain Definition for Mode Sepolia
 */
export const modeSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Mode Sepolia',
  id: 919,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.mode.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Mode Sepolia Explorer',
      url: 'https://sepolia.explorer.mode.network',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[919] ? chainContracts[11155111][919] : {}),
    portal: {
      11155111: {
        address: '0x320e1580effF37E008F1C92700d1eBa47c1B23fD',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xbC5C679879B2965296756CD959C3C739769995E2',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x015a8c2e0a5fEd579dbb05fd290e413Adc6FC24A',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xc19a60d9E8C27B9A43527c3283B4dd8eDC8bE15C',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x15cd4f6e0CE3B4832B33cB9c6f6Fe6fc246754c2',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x7Bb634B42373A87712Da14064deD13Db8b8b14f4',
      },
    },
  },
})

/**
 * Chain Definition for OP Sepolia
 */
export const opSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'OP Sepolia',
  id: 11155420,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.optimism.io'],
    },
  },
  blockExplorers: {
    default: {
      name: 'OP Sepolia Explorer',
      url: 'https://testnet-explorer.optimism.io',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[11155420]
      ? chainContracts[11155111][11155420]
      : {}),
    portal: {
      11155111: {
        address: '0x16Fc5058F25648194471939df75CF27A2fdC48BC',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xFBb0621E0B23b5478B630BD55a5f21f67730B0F1',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xd83e03D576d23C9AEab8cC44Fa98d058D2176D1f',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x034edD2A225f7f429A63E0f1D2084B9E0A93b538',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x05F9613aDB30026FFd634f38e5C4dFd30a197Fa1',
      },
    },
  },
})

/**
 * Chain Definition for Ozean Poseidon Sepolia
 */
export const ozeanSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Ozean Poseidon Sepolia',
  id: 7849306,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'USDX',
    symbol: 'USDX',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://ozean-testnet.rpc.caldera.xyz/http'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Ozean Poseidon Sepolia Explorer',
      url: 'https://ozean-testnet.explorer.caldera.xyz',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[7849306]
      ? chainContracts[11155111][7849306]
      : {}),
    portal: {
      11155111: {
        address: '0x6EeeA09335D09870dD467FD34ECc10Fdb5106527',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xb9558CE3C11EC69e18632A8e5B316581e852dB91',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x50d26235319abF2bA7b043A33E53bD19480d7E69',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x13931872294360cAc551BA3801f061c4C86F0725',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xdEC733B0643E7c3Bd06576A4C70Ca87E301EAe87',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x80E233699F34b8FD91adea8150Ea4C91b9324Cb5',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0x591d916DD9C0c37Ae5b23593C79f5074aAF6778F',
      },
    },
  },
})

/**
 * Chain Definition for Pivotal Sepolia
 */
export const pivotalSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Pivotal Sepolia',
  id: 16481,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.pivotalprotocol.com/'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Pivotal Sepolia Explorer',
      url: 'https://sepolia.pivotalscan.org/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[16481]
      ? chainContracts[11155111][16481]
      : {}),
    portal: {
      11155111: {
        address: '0x923B28e0037A799A1e60368e60c92dFfba982162',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x788De2B0Dd35808a05eAFf7aAf5578B21E0dd9A7',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x079ba88EDD1BE4FEFb5011B61714Df9eF092Ad8f',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x1F6393C113b9C221fbcFB17c163C88d4bDa172b0',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x5C72CE6EA707037bC476dA8f4f969bC1f8abc78b',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xcB97C9224Af16C95b8D8959A2752eF1832EB8BA9',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0x8A5F3B0897d9B9bA09fd2974F3aBE038C15AaBa9',
      },
    },
  },
})

/**
 * Chain Definition for Race Sepolia
 */
export const raceSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Race Sepolia',
  id: 6806,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://racetestnet.io'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Race Sepolia Explorer',
      url: 'https://testnet.racescan.io/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[6806] ? chainContracts[11155111][6806] : {}),
    portal: {
      11155111: {
        address: '0xF2891fc6819CDd6BD9221874619BB03A6277d72A',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x289179e9d43A35D47239456251F9c2fdbf9fbeA2',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xBafb1a6e54e7750aF29489D65888d1c96Dfd66Df',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xdaeab17598938A4f27E50AC771249Ad7df12Ea7D',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x07e7A3F25aA73dA15bc19B71FEF8f5511342a409',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xbDC16b0E8C18C5E13Ed02221Aa85598AF486A88f',
      },
    },
  },
})

/**
 * Chain Definition for Radius Sepolia
 */
export const radiusTestnetSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Radius Sepolia',
  id: 863,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['testnet-rpc.theradius.xyz'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Radius Sepolia Explorer',
      url: 'https://testnet-rpc.theradius.xyz/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[863] ? chainContracts[11155111][863] : {}),
    portal: {
      11155111: {
        address: '0x86897210aaD2861Aa603937762AC7c1E6Dfa9727',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xD5983849E1EBFDb97e66736962Dbf9dB4d2BDC08',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x3099397312B675f629E2C2d85A0744FCaf7bf325',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x00faA26c5e3483a78d2ca28edc5275B9a42AC8c2',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x59b71c0a919bC1E8daE5488A562215494f1257fe',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x6D6eF1D3a2eCC7511a0881F460422B461CA7128a',
      },
    },
  },
})

/**
 * Chain Definition for Settlus Sepolia
 */
export const settlusSepoliaSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Settlus Sepolia',
  id: 5373,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://settlus-septestnet.g.alchemy.com/public'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Settlus Sepolia Explorer',
      url: 'sepolia.settlus.network',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[5373] ? chainContracts[11155111][5373] : {}),
    portal: {
      11155111: {
        address: '0x55585368857DcC7E0F89475d28963977DB0b1Ee1',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x1Fe9c3b11Ed334fC049aE9a92Ec290aA69C39267',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0xbD07617F0Ce47DB1cd51Eb6b9b5E7b3c109410F2',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xffAe0c2cf1547057CD0828e3B01aF11C266C1b3C',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x7f73514A7eC19f3F51E3c607D536560818dF4205',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x017D15a6854CCAaa89c63d1A9fea8da45Ced97Cf',
      },
    },
  },
})

/**
 * Chain Definition for Shape Sepolia
 */
export const shapeSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Shape Sepolia',
  id: 11011,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.shape.network/'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Shape Sepolia Explorer',
      url: 'https://shape-sepolia.explorer.alchemy.com/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[11011]
      ? chainContracts[11155111][11011]
      : {}),
    portal: {
      11155111: {
        address: '0xfF8Ca2B4d8122E41441F7ccDCf61b8692198Bd1E',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x341ab1DAFdfB73b3D6D075ef10b29e3cACB2A653',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x19f02c55254d2644eF94f30C74A932D64e1D4F86',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0xF9F730650e1AB4D23E2ac983934271ca7c5EF293',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xa1aC91ED91EbE40E00d61E233c8026318b4da5fb',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x575697F2c20Bd63415E5B24656d935D4b81b8220',
      },
    },
  },
})

/**
 * Chain Definition for Soneium  Minato Sepolia
 */
export const soneiumMinatoSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Soneium  Minato Sepolia',
  id: 1946,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.minato.soneium.org'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Soneium  Minato Sepolia Explorer',
      url: 'https://soneium-minato.blockscout.com/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[1946] ? chainContracts[11155111][1946] : {}),
    portal: {
      11155111: {
        address: '0x65ea1489741A5D72fFdD8e6485B216bBdcC15Af3',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x5f5a404A5edabcDD80DB05E8e54A78c9EBF000C2',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x2bfb22cd534a462028771a1cA9D6240166e450c4',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x0184245D202724dc28a2b688952Cb56C882c226F',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x4Ca9608Fef202216bc21D543798ec854539bAAd3',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xB3Ad2c38E6e0640d7ce6aA952AB3A60E81bf7a01',
      },
    },
  },
})

/**
 * Chain Definition for Binary Sepolia
 */
export const tbnSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Binary Sepolia',
  id: 625,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Test BNRY',
    symbol: 'TBNRY',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.testnet.thebinaryholdings.com'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Binary Sepolia Explorer',
      url: 'https://explorer.sepolia.thebinaryholdings.com',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[625] ? chainContracts[11155111][625] : {}),
    portal: {
      11155111: {
        address: '0xFBEd910ca54F013bfeA67Bd4DC836263bdd0b46C',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x3B78C3B41b3e3fC6bdf0bD3060C9E2471401C098',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x7c95EebEA6f68875b4093D9c2211Fd26067a808F',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x33Dc556A5df0B8998dC2640c78E531Ae1dB7925d',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x1a6D0312FaaaCa2BF818660F164450176C6205C9',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x096b38bDC80B5BF5B5Fb4e1A75Ae38BDa520474A',
      },
    },
    l2OutputOracle: {
      11155111: {
        address: '0xF3699f96cBdD3868B64352669805D96d1Fb6431d',
      },
    },
  },
})

/**
 * Chain Definition for Unichain Sepolia
 */
export const unichainSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Unichain Sepolia',
  id: 1301,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.unichain.org'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Unichain Sepolia Explorer',
      url: 'https://sepolia.uniscan.xyz',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[1301] ? chainContracts[11155111][1301] : {}),
    portal: {
      11155111: {
        address: '0x0d83dab629f0e0F9d36c0Cbc89B69a489f0751bD',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xea58fcA6849d79EAd1f26608855c2D6407d54Ce2',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x4696b5e042755103fe558738Bcd1ecEe7A45eBfe',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x448A37330A60494E666F6DD60aD48d930AEbA381',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xaeE94b9aB7752D3F7704bDE212c0C6A0b701571D',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xeff73e5aa3B9AEC32c659Aa3E00444d20a84394b',
      },
    },
  },
})

/**
 * Chain Definition for World Chain Sepolia
 */
export const worldchainSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'World Chain Sepolia',
  id: 4801,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://worldchain-sepolia.g.alchemy.com/public'],
    },
  },
  blockExplorers: {
    default: {
      name: 'World Chain Sepolia Explorer',
      url: 'https://worldchain-sepolia.explorer.alchemy.com/',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[4801] ? chainContracts[11155111][4801] : {}),
    portal: {
      11155111: {
        address: '0xFf6EBa109271fe6d4237EeeD4bAb1dD9A77dD1A4',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0xd7DF54b3989855eb66497301a4aAEc33Dbb3F8DE',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x3580505c56f8560E3777E92Fb27f70fD20c5B493',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x7768c821200554d8F359A8902905Ba9eDe5659a9',
      },
    },
    systemConfig: {
      11155111: {
        address: '0x166F9406e79A656f12F05247fb8F5DfA6155bCBF',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0x8Ec1111f67Dad6b6A93B3F42DfBC92D81c98449A',
      },
    },
  },
})

/**
 * Chain Definition for Zora Sepolia
 */
export const zoraSepolia = /*#__PURE__*/ defineChain({
  ...chainConfig,
  name: 'Zora Sepolia',
  id: 999999999,
  sourceId: 11155111,
  nativeCurrency: {
    name: 'Ether',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://sepolia.rpc.zora.energy'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Zora Sepolia Explorer',
      url: 'https://sepolia.explorer.zora.energy',
    },
  },
  contracts: {
    ...opContracts,
    ...(chainContracts[11155111]?.[999999999]
      ? chainContracts[11155111][999999999]
      : {}),
    portal: {
      11155111: {
        address: '0xeffE2C6cA9Ab797D418f0D91eA60807713f3536f',
      },
    },
    l1StandardBridge: {
      11155111: {
        address: '0x5376f1D543dcbB5BD416c56C189e4cB7399fCcCB',
      },
    },
    l1Erc721Bridge: {
      11155111: {
        address: '0x16B0a4f451c4CB567703367e587E15Ac108e4311',
      },
    },
    l1CrossDomainMessenger: {
      11155111: {
        address: '0x1bDBC0ae22bEc0c2f08B4dd836944b3E28fe9b7A',
      },
    },
    systemConfig: {
      11155111: {
        address: '0xB54c7BFC223058773CF9b739cC5bd4095184Fb08',
      },
    },
    disputeGameFactory: {
      11155111: {
        address: '0xA983A71253Eb74e5E86A4E4eD9F37113FC25f2BF',
      },
    },
  },
})

export const sepoliaChains = [
  arenaZSepolia,
  baseSepolia,
  bobaSepolia,
  campSepolia,
  creatorChainSepolia,
  cyberSepolia,
  ethernitySepolia,
  funkiSepolia,
  inkSepolia,
  liskSepolia,
  metalSepolia,
  modeSepolia,
  opSepolia,
  ozeanSepolia,
  pivotalSepolia,
  raceSepolia,
  radiusTestnetSepolia,
  settlusSepoliaSepolia,
  shapeSepolia,
  soneiumMinatoSepolia,
  tbnSepolia,
  unichainSepolia,
  worldchainSepolia,
  zoraSepolia,
]

export const sepoliaNetwork: Network = {
  name: 'sepolia',
  sourceChain: viemChains.sepolia,
  chains: sepoliaChains,
}
