// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import { defineChain } from 'viem'
import { chainConfig } from 'viem/op-stack'

export const devnetL1 = defineChain({
  id: 900,
  name: 'Devnet L1',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['http://localhost:8545'],
    },
  },
})

export const devnetL2 = defineChain({
  ...chainConfig,
  id: 901,
  name: 'Devnet L2',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['http://localhost:9545'],
    },
  },
  sourceId: 900,
})

export const orderlyNetwork = defineChain({
  ...chainConfig,
  id: 291,
  name: 'Orderly Network',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.orderly.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.orderly.network',
    },
  },
  sourceId: 1,
})

export const lyra = defineChain({
  ...chainConfig,
  id: 957,
  name: 'Lyra',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.lyra.finance'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.lyra.finance',
    },
  },
  sourceId: 1,
})

export const mode = defineChain({
  ...chainConfig,
  id: 34443,
  name: 'Mode',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://mainnet.mode.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.mode.network',
    },
  },
  sourceId: 1,
})
