// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import { defineChain } from 'viem'
import { chainConfig } from 'viem/op-stack'

export const orderlyNetwork = defineChain({
  ...chainConfig,
  id: 291,
  name: 'Orderly Network',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.orderly.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.orderly.network',
    },
  },
  sourceId: 1,
})

export const lyra = defineChain({
  ...chainConfig,
  id: 957,
  name: 'Lyra',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.lyra.finance'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.lyra.finance',
    },
  },
  sourceId: 1,
})

export const mode = defineChain({
  ...chainConfig,
  id: 34443,
  name: 'Mode',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.mode.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.mode.network',
    },
  },
  sourceId: 1,
})
